name: Handling issues
on: [issues, workflow_dispatch]
jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - name: Info on event details
              run: echo "${{ toJson(github) }}"