name: Practice
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v4
            - name: Install Dependencies
              run: npm ci
            - name: Lint Check
              run: npm run lint
    test:
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v4
            - name: Install Dependencies
              run: npm ci
            - name: Test-code
              run: npm test
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v4
            - name: Install Dependencies
              run: npm ci
            - name: Building
              run: npm run build
            - name: Message
              run: echo "Done with the jobs" 